### ISSUE TITLE
I can't close the webcam

### ISSUE THREAD

**Issue by cancaglar** [keijiro/SelfieBarracuda#11]
When I change scene or close the app my webcam (logitech brio 4k) not shutting down itself and of course ImageSorce.cs class can't editable so I can't do anything. Please help.

**Comment by keijiro** [comment]
Sorry, I can't understand what you're trying to tell. Could you try rephrasing it in simple and plain but detailed text?

**Comment by cancaglar** [comment]
My webcam doesn't turn off when I switch scenes in game. There is have a class called Compositor.cs and in this class there is have OnDestroy method you are destroying or disposing the webcam in that method but its not working I guess because webcam doesn't turn off. I hope I was more descriptive.

**Comment by keijiro** [comment]
This project doesn't do anything about webcam. The [TestTools](https://github.com/keijiro/TestTools) package manages it instead.

If you have find an issue with the TestTools package, please submit an issue to the TestTools repository instead of this repository.

**Comment by keijiro** [comment]
I'm closing this issue now as "not relevant". Please reopen it for further problems with this project.
