### ISSUE TITLE
Use this plugin in URP Project

### ISSUE THREAD

**Issue by RameChoi** [keijiro/SelfieBarracuda#12]
When you insert URP asset into Graphics and Quality, nothing is displayed in the image. If you insert only one of the two, nothing will be displayed.

**Comment by keijiro** [comment]
Unfortunately, the sample project only runs on the builtin render pipeline.

On the other hand, the SelfieBarracuda package (jp.keijiro.mediapipe.selfie) is compatible with URP.

Please let me know if you find any issue with the package running on URP.
