### ISSUE TITLE
WebGL build 

### ISSUE THREAD

**Issue by LoopIssuer** [keijiro/SelfieBarracuda#13]
Hi,
Is there a way to run your Barracuda Selfie Segmentation project on WebGL?
Thank you in advance for any help.

**Comment by keijiro** [comment]
That's technically possible but a bit difficult.

You may have to use WebGL2 and the pixel shader NN worker. I haven't tested these features yet, so I'm not sure if it actually works.

You may have to invest significant amount of time to modify the code and test the features. I'd recommend looking for other solutions if you don't have time for it.

If you have time for it, contribution would be welcomed by the community.

**Comment by keijiro** [comment]
I'm closing this issue now because I don't have time to deep dive into this direction at the moment. I'll revisit it when I get ready for it or get good news about the features.
