### ISSUE TITLE
Where to get MediaPipe Meet Segmentation Model?

### ISSUE THREAD

**Issue by XinJiang1994** [keijiro/SelfieBarracuda#2]
I can only find the model card. But I don't know how to get the tflite files. Are there any ways to get the tflite files?

**Comment by keijiro** [comment]
I only know where the ONNX file is because Barracuda only supports ONNX.

Please check README for the ONNX file.

**Comment by keijiro** [comment]
I'm closing this issue as the question is irrelevant. Please feel free to reopen it for further problems.
