### ISSUE TITLE
[Android Build] RenderTexture.Create failed: format unsupported for random writes

### ISSUE THREAD

**Issue by Fenikkel** [keijiro/SelfieBarracuda#4]
Hi there,

In "play mode", everything goes fine with every mode, but when I make a build for Android, the Android Logcat complains about this error: 

- **RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).**
- **Unity.Barracuda.ReferenceComputeOps:TensorToRenderTexture(Tensor, RenderTexture, Int32, Int32, Vector4, Vector4, Texture3D)**
- **MediaPipe.Selfie.SegmentationFilter:RunModel(Texture)**
- **Compositor:Update()**

I tested initialize the RenderTexture with other [formats](https://docs.unity3d.com/ScriptReference/RenderTextureFormat.html) (Defauld, ARGB32 and R16) but throw the same errors.

Any idea how I should build correctly for Android ?

Tested on a Tablet (Android 11) and a old movile (Android 9)

**Comment by keijiro** [comment]
It seems that your devices don't support UAV (unordered access views) with render textures.

I should find a workaround for it, but at the moment there is no workaround for this problem.

FYI: My Android device (Pixel 5) supports UAV, so it runs flawlessly.

**Comment by Fenikkel** [comment]
Thanks for the answer @keijiro  

> It seems that your devices don't support UAV (unordered access views) with render textures.

I don't know if i'm doing correctly the search but I don't find a list of compatible devices with UAV. Do you know some  compatible devices? I'm interested in tablets.

**Comment by keijiro** [comment]
If I understand it correctly, it requires `shaderStorageImageExtendedFormats`.

https://vulkan.gpuinfo.org/listdevicescoverage.php?feature=shaderStorageImageExtendedFormats&platform=all

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by shreks7** [comment]
@keijiro Any updates on this? 

I am using OpenGLES (with AVPro - they don't support Vulkan) and getting  
`RenderTexture.Create failed: format unsupported for random writes - R16 SFloat (45).`   (Samsung Galaxy Tab S8)

Here is what is supported - 
 - `RFloat`
 - `ARGB32`
 - `ARGBHalf`
 - `ARGBFloat`
 - `RInt`
 - `ARGBInt`
 - `RGBAUShort`
 
I switched to `RFloat` but I am sure that is excessive for this.

**Comment by keijiro** [comment]
> I switched to RFloat but I am sure that is excessive for this.

You should use RFloat in that case.
