### ISSUE TITLE
How to reduce lag in android devices?

### ISSUE THREAD

**Issue by kapupararavi** [keijiro/SelfieBarracuda#6]
How to reduce lag in android devices? For example, if I move my head to the right it moves in devices after few seconds.

**Comment by keijiro** [comment]
Please check this: https://github.com/keijiro/HandPoseBarracuda/issues/7

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by kapupararavi** [comment]
The files described in the HandPoseBarracuda are not available in this project. But, I have made changes in ResourceSet.cs and SegmentationFilter.cs as below. Still I am having lag in my android device. Do I have to change anything else to make it run on a CPU?
![image_2021_11_10T11_59_27_395Z](https://user-images.githubusercontent.com/40574114/141109893-425af858-0b1b-439f-a84d-ccff0dd9fa10.png)
![image_2021_11_10T12_00_28_643Z](https://user-images.githubusercontent.com/40574114/141109895-6bdb4fb5-7c17-4635-8e49-23ddb3818fa8.png)
![image_2021_11_10T12_01_25_379Z](https://user-images.githubusercontent.com/40574114/141109882-73e961bc-8349-4096-83e4-befa66cc5822.png)

**Comment by keijiro** [comment]
Which device are you using? I wonder if your device has enough processing power to run the NN model.

**Comment by kapupararavi** [comment]
I am using Samsung Galaxy A50 (https://www.gsmarena.com/samsung_galaxy_a50-9554.php)

**Comment by keijiro** [comment]
I think you should use Profiler to get insight of where the slowest part is.

**Comment by kapupararavi** [comment]
Profiler is around at 30 fps for scripting.

**Comment by keijiro** [comment]
Did you connect the profile to the device?
