### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by hiddenDevXR** [keijiro/SelfieBarracuda#8]
Hi! First of all: awesome work! Thank you very much to have this available for all of us.

Wanted to ask if this works on WebGL. I made the WebGL build but I am only getting a white texture.

Much apreciated!

**Comment by keijiro** [comment]
Barracuda on WebGL only supports CPU inference while this sample uses GPU inference.

You may be able to change it to use CPU inference, although I have never tried it.

Please check the Barracuda documentation for details.
